# Generated by Django 2.0.3 on 2019-04-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190403_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datasets',
            new_name='Dataset',
        ),
    ]
