# Generated by Django 2.0.3 on 2019-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190403_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='TrainingModel',
            new_name='ClassificationModel',
        ),
    ]
